name: Check code

on:

  push:
    branches: [ dev, master ]
    paths:
      - '**'
      - '!RELEASE.md'
      - '!LICENSE'
      - '!README.md'
  pull_request:
    branches: [ master ]

jobs:

  Check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create package link folder
      run: |
        ln -sf src rp2paths

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 bandit

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test for security flaws with bandit
      run: |
        bandit -r . -lll  # -lll to only catch the higher level security issues
