name: Publish

on:
  push:
    branches: [ fix-publish-workflow ]
#    branches: [ stable ]
#    paths:
#      - 'RELEASE.md'

jobs:

#  PyPi:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.x'
#    - name: Install dependencies
#      run: |
#        pip install setuptools wheel twine
#    - name: Build
#      run: |
#        python setup.py sdist bdist_wheel
#    - name: Upload
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        twine upload dist/* --verbose

  Conda:
    runs-on: ubuntu-latest

    env:
      ANACONDA_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      ANACONDA_USER: ${{secrets.ANACONDA_USER}}
      ANACONDA_LABEL: main
      CONDA_BLD_PATH: /tmp/conda-bld

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: build_env
        auto-update-conda: true
        environment-file: recipe/conda_build_env.yaml
        miniconda-version: "latest"
        auto-activate-base: false

    - name: Set up output folder
      run: |
        mkdir -p ${CONDA_BLD_PATH}

    - name: Build conda package
      shell: bash -l {0}
      run: |
        conda build -c conda-forge -c cyclus --output-folder ${CONDA_BLD_PATH} recipe

    - name: Convert to other platforms
      shell: bash -l {0}
      run: |
        conda convert \
          --platform osx-64 \
          --platform linux-64 \
          --platform win-64 \
          --output-dir ${CONDA_BLD_PATH} \
          ${CONDA_BLD_PATH}/*/rpreactor-*

    - name: Upload to anaconda
      shell: bash -l {0}
      run: |
        anaconda \
          --token ${ANACONDA_TOKEN} \
          upload \
          --user ${ANACONDA_USER} \
          --label ${ANACONDA_LABEL} \
          ${CONDA_BLD_PATH}/*/rp2paths-*.tar.bz2
